M48
; DRILL file {KiCad 7.0.9} date Tue 23 Jan 2024 06:46:13 PM PST
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-01-23T18:46:13-08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.9
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0591
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0709
%
G90
G05
T1
X3.3545Y-0.7144
X3.5455Y-0.7144
T2
X3.3427Y-0.5951
X3.5573Y-0.5951
T0
M30
